[package]
name = "tqapi"
version = "0.1.0"
authors = ["Xu Tiezhu <xutiezhu@gmail.com>"]
edition = "2018"
build = "build.rs"

[dependencies]
libc = "~0.2"
chrono = "~0.4"
serde = { version = "~1.0", features = ["derive"] }
serde_json = "~1.0"
