/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_acqusta_tquant_api_impl_TQuantApiJni */

#ifndef _Included_com_acqusta_tquant_api_impl_TQuantApiJni
#define _Included_com_acqusta_tquant_api_impl_TQuantApiJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_acqusta_tquant_api_impl_TQuantApiJni
 * Method:    create
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_acqusta_tquant_api_impl_TQuantApiJni_create
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_acqusta_tquant_api_impl_TQuantApiJni
 * Method:    destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_acqusta_tquant_api_impl_TQuantApiJni_destroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_acqusta_tquant_api_impl_TQuantApiJni
 * Method:    getTradeApi
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_acqusta_tquant_api_impl_TQuantApiJni_getTradeApi
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_acqusta_tquant_api_impl_TQuantApiJni
 * Method:    getDataApi
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_acqusta_tquant_api_impl_TQuantApiJni_getDataApi
  (JNIEnv *, jclass, jlong, jstring);

#ifdef __cplusplus
}
#endif
#endif
