/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_acqusta_tquant_stralet_impl_StraletJni */

#ifndef _Included_com_acqusta_tquant_stralet_impl_StraletJni
#define _Included_com_acqusta_tquant_stralet_impl_StraletJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_acqusta_tquant_stralet_impl_StraletJni
 * Method:    create
 * Signature: (Lcom/acqusta/tquant/stralet/Stralet;)J
 */
JNIEXPORT jlong JNICALL Java_com_acqusta_tquant_stralet_impl_StraletJni_create
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_acqusta_tquant_stralet_impl_StraletJni
 * Method:    destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_acqusta_tquant_stralet_impl_StraletJni_destroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_acqusta_tquant_stralet_impl_StraletJni
 * Method:    runBacktest
 * Signature: (Ljava/lang/String;Lcom/acqusta/tquant/stralet/StraletCreator;)V
 */
JNIEXPORT void JNICALL Java_com_acqusta_tquant_stralet_impl_StraletJni_runBacktest
  (JNIEnv *, jclass, jstring, jobject);

/*
 * Class:     com_acqusta_tquant_stralet_impl_StraletJni
 * Method:    runRealTime
 * Signature: (Ljava/lang/String;Lcom/acqusta/tquant/stralet/StraletCreator;)V
 */
JNIEXPORT void JNICALL Java_com_acqusta_tquant_stralet_impl_StraletJni_runRealTime
  (JNIEnv *, jclass, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
