/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_acqusta_tquant_api_impl_TradeApiJni */

#ifndef _Included_com_acqusta_tquant_api_impl_TradeApiJni
#define _Included_com_acqusta_tquant_api_impl_TradeApiJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_acqusta_tquant_api_impl_TradeApiJni
 * Method:    create
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_acqusta_tquant_api_impl_TradeApiJni_create
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_acqusta_tquant_api_impl_TradeApiJni
 * Method:    destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_acqusta_tquant_api_impl_TradeApiJni_destroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_acqusta_tquant_api_impl_TradeApiJni
 * Method:    queryAccountStatus
 * Signature: (J)[Lcom/acqusta/tquant/api/TradeApi/AccountInfo;
 */
JNIEXPORT jobjectArray JNICALL Java_com_acqusta_tquant_api_impl_TradeApiJni_queryAccountStatus
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_acqusta_tquant_api_impl_TradeApiJni
 * Method:    queryBalance
 * Signature: (JLjava/lang/String;)Lcom/acqusta/tquant/api/TradeApi/Balance;
 */
JNIEXPORT jobject JNICALL Java_com_acqusta_tquant_api_impl_TradeApiJni_queryBalance
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_acqusta_tquant_api_impl_TradeApiJni
 * Method:    queryOrders
 * Signature: (JLjava/lang/String;)[Lcom/acqusta/tquant/api/TradeApi/Order;
 */
JNIEXPORT jobjectArray JNICALL Java_com_acqusta_tquant_api_impl_TradeApiJni_queryOrders
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_acqusta_tquant_api_impl_TradeApiJni
 * Method:    queryTrades
 * Signature: (JLjava/lang/String;)[Lcom/acqusta/tquant/api/TradeApi/Trade;
 */
JNIEXPORT jobjectArray JNICALL Java_com_acqusta_tquant_api_impl_TradeApiJni_queryTrades
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_acqusta_tquant_api_impl_TradeApiJni
 * Method:    queryPositions
 * Signature: (JLjava/lang/String;)[Lcom/acqusta/tquant/api/TradeApi/Position;
 */
JNIEXPORT jobjectArray JNICALL Java_com_acqusta_tquant_api_impl_TradeApiJni_queryPositions
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_acqusta_tquant_api_impl_TradeApiJni
 * Method:    placeOrder
 * Signature: (JLjava/lang/String;Ljava/lang/String;DJLjava/lang/String;I)Lcom/acqusta/tquant/api/TradeApi/OrderID;
 */
JNIEXPORT jobject JNICALL Java_com_acqusta_tquant_api_impl_TradeApiJni_placeOrder
  (JNIEnv *, jclass, jlong, jstring, jstring, jdouble, jlong, jstring, jint);

/*
 * Class:     com_acqusta_tquant_api_impl_TradeApiJni
 * Method:    cancelOrder
 * Signature: (JLjava/lang/String;Ljava/lang/String;I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_acqusta_tquant_api_impl_TradeApiJni_cancelOrder__JLjava_lang_String_2Ljava_lang_String_2I
  (JNIEnv *, jclass, jlong, jstring, jstring, jint);

/*
 * Class:     com_acqusta_tquant_api_impl_TradeApiJni
 * Method:    cancelOrder
 * Signature: (JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_acqusta_tquant_api_impl_TradeApiJni_cancelOrder__JLjava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jclass, jlong, jstring, jstring, jstring);

/*
 * Class:     com_acqusta_tquant_api_impl_TradeApiJni
 * Method:    query
 * Signature: (JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_acqusta_tquant_api_impl_TradeApiJni_query
  (JNIEnv *, jclass, jlong, jstring, jstring, jstring);

/*
 * Class:     com_acqusta_tquant_api_impl_TradeApiJni
 * Method:    setCallback
 * Signature: (JLcom/acqusta/tquant/api/TradeApi/Callback;)V
 */
JNIEXPORT void JNICALL Java_com_acqusta_tquant_api_impl_TradeApiJni_setCallback
  (JNIEnv *, jclass, jlong, jobject);

#ifdef __cplusplus
}
#endif
#endif
