/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_acqusta_tquant_api_impl_TQuantApiJni */

#ifndef _Included_com_acqusta_tquant_api_impl_TQuantApiJni
#define _Included_com_acqusta_tquant_api_impl_TQuantApiJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_acqusta_tquant_api_impl_TQuantApiJni
 * Method:    setParams
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_acqusta_tquant_api_impl_TQuantApiJni_setParams
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
